In [2]:
import pandas as pd
import os

In [5]:
path = '/Users/oesikgogi/Desktop/도서관 정보나루'
files = [f for f in os.listdir(path) if f.endswith('.xlsx')]

In [6]:
combined_df = pd.concat([pd.read_excel(os.path.join(path, file)) for file in files], ignore_index=True)
combined_df

/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,편의점 비밀 요원:박주혜 동화,박주혜 지음;정인하 그림,창비,2020,9788936451585,NaN,7,58,808.9,1,1,2024-09-21
1,2,말괄량이 길들이기,"양태석,셰익스피어 원작,김혜연 그림",은하수미디어,2024,9788965795940,NaN,7,58,808.9,1,1,2024-09-21
2,3,루미너스 오늘부터 데뷔합니다,김영주 글;하티 그림,다산어린이,2024,9791130655222,NaN,7,2,813.8,1,1,2024-09-21
3,4,도시 해킹,한수연 지음,책빛,2024,9788962194685,NaN,7,81,808.9,1,0,2024-09-21
4,5,내가 똑똑하다고?,김윤아 글;강은옥 그림,천개의바람,2024,9791165735586,NaN,7,NaN,813.8,1,1,2024-09-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
317417,631,용감한 아이린,윌리엄 스타이그 글·그림;김서정 옮김,웅진닷컴,2012.0,9788901031774,NaN,7.0,NaN,843.0,1,1,2014-01-16
317418,632,날아라 슝슝 공,김용란 글;김유대 그림,웅진씽크빅,2010.0,9788901115061,NaN,7.0,NaN,695.0,1,0,2014-01-16
317419,633,수학 귀신,한스 마그누스 엔첸스베르거 지음;로트라우트 수잔네 베르너 그림;고영아 옮김,비룡소,2011.0,9788949190013,NaN,4.0,NaN,410.0,1,3,2014-01-16
317420,634,돼지가 한 마리도 죽지 않던 날,로버트 뉴턴 펙 지음;김옥수 옮김,사계절,2008.0,9788958280934,NaN,4.0,NaN,843.0,1,4,2014-01-16
317421,635,여행의 기술:알랭 드 보통의 여행 에세이,알랭 드 보통 씀;정영목 옮김,이레,2004.0,9788957090268,NaN,0.0,NaN,844.0,1,1,2014-01-16

In [8]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 317422 entries, 0 to 317421
Data columns (total 13 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   번호       317422 non-null  int64
 1   도서명      317421 non-null  object
 2   저자       317360 non-null  object
 3   출판사      315627 non-null  object
 4   발행년도     317083 non-null  object
 5   ISBN     317422 non-null  int64
 6   세트 ISBN  22086 non-null   float64
 7   부가기호     182583 non-null  object
 8   권        47717 non-null   object
 9   주제분류번호   317311 non-null  object
 10  도서권수     317422 non-null  int64
 11  대출건수     317422 non-null  int64
 12  등록일자     317422 non-null  object
dtypes: float64(1), int64(4), object(8)
memory usage: 31.5+ MB

In [12]:
combined_df.drop(['번호', '세트 ISBN', '부가기호', '권', '도서권수', '대출건수', '등록일자'], axis=1, inplace=True)

In [15]:
# ISBN 컬럼을 기준으로 중복된 행 삭제
combined_df = combined_df.drop_duplicates(subset='ISBN', keep='first')

In [34]:
combined_df.reset_index(inplace=True)

In [39]:
combined_df.drop('index', axis=1, inplace=True)

/var/folders/vb/43mrc_5n7lv3mxvw35wxbz9h0000gn/T/ipykernel_6144/3389425790.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df.drop('index', axis=1, inplace=True)

In [35]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182368 entries, 0 to 182367
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   index   182368 non-null  int64
 1   도서명     182368 non-null  object
 2   저자      182368 non-null  object
 3   출판사     180915 non-null  object
 4   발행년도    182266 non-null  object
 5   ISBN    182368 non-null  int64
 6   주제분류번호  182279 non-null  object
dtypes: int64(2), object(5)
memory usage: 9.7+ MB

In [36]:
combined_df[combined_df['출판사'].isnull()]

,index,도서명,저자,출판사,발행년도,ISBN,주제분류번호
624,624,심심이 세 개,김자연 글;최지경 그림,NaN,2022,9791192054094,813.8
1287,1287,계란 좀 빌려줄래요,장수경 지음,NaN,2023,9788958070009,813.8
1290,1290,(The) Cool bean,by Jory John;illustrated by Pete Oswald,NaN,2010,9780063030756,843
1933,1933,May i please have a cookie?,Jennifer E. Morris,NaN,2021,9789815013573,747
2264,2264,다산의 마지막 질문:나를 깨닫는다는 것,조윤제 지음,NaN,2022,9788935214303,151.581
...,...,...,...,...,...,...,...
169635,169654,Curious George =,by Cynthina Platt,NaN,2020,9780358169024,843
169636,169655,Curious George =,by Margret Rey,NaN,2019,9780358157229,843
169685,169704,Say something =,by Peter H Reynolds,NaN,2019,9789811174827,843
169692,169711,It's only Stanley =,by Jon Agee,NaN,2020,9781912650477,843
182023,182044,차크라 바르틴-하,성낙주,NaN,1995,2002954000387,813.6

In [28]:
combined_df = combined_df.dropna(subset=['저자'])

In [37]:
# 발행년도와 출판사의 결측치를 0으로 채우기
combined_df['발행년도'] = combined_df['발행년도'].fillna(0)
combined_df['출판사'] = combined_df['출판사'].fillna(0)

/var/folders/vb/43mrc_5n7lv3mxvw35wxbz9h0000gn/T/ipykernel_6144/2564903152.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df['발행년도'] = combined_df['발행년도'].fillna(0)
/var/folders/vb/43mrc_5n7lv3mxvw35wxbz9h0000gn/T/ipykernel_6144/2564903152.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df['출판사'] = combined_df['출판사'].fillna(0)

In [40]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182368 entries, 0 to 182367
Data columns (total 6 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   도서명     182368 non-null  object
 1   저자      182368 non-null  object
 2   출판사     182368 non-null  object
 3   발행년도    182368 non-null  object
 4   ISBN    182368 non-null  int64
 5   주제분류번호  182279 non-null  object
dtypes: int64(1), object(5)
memory usage: 8.3+ MB

In [41]:
combined_df.tail()

,도서명,저자,출판사,발행년도,ISBN,주제분류번호
182363,토지,박경리 지음,나남출판,2005.0,9788930007085,813.6
182364,토지,박경리 지음,나남출판,2005.0,9788930007078,813.6
182365,"자전거, 도무지 헤어나올 수 없는 아홉 가지 매력",윤준호 [외] 지음,지성사,2009.0,9788978892001,698.97
182366,용감한 아이린,윌리엄 스타이그 글·그림;김서정 옮김,웅진닷컴,2012.0,9788901031774,843.0
182367,돼지가 한 마리도 죽지 않던 날,로버트 뉴턴 펙 지음;김옥수 옮김,사계절,2008.0,9788958280934,843.0

In [42]:
combined_df['발행년도'].astype(int)

ValueError: invalid literal for int() with base 10: '2021-2023'

In [ ]:
# 주제분류번호